import type { LivingModelState } from "./types";

const now = "2026-08-29T09:10:00.000Z";

export const DEMO_STATE: LivingModelState = {
  schemaVersion: 1,
  mode: "demo",
  agentRuntimeStatus: "unavailable",
  onboarded: true,
  onboardingReasons: ["Understand myself better", "Navigate a change"],
  sampleDataLoaded: true,
  hasPersonalUnderstanding: false,
  memoryPaused: false,
  preferences: { tone: 42, depth: 58, practicalSuggestions: true, notes: "Be direct when the pattern is supported, but leave room for me to disagree." },
  sessions: [
    {
      id: "session-career-aug29",
      input: "I tried a reversible first step before treating the career decision as final.",
      context: "decision",
      state: "COMPLETE",
      clarification: "Keeping my own judgement while learning from the test.",
      structure: { reality: "The decision is still open, but I have new direct experience.", expectation: "Other people still have preferences about what I choose.", selfDoubt: "Uncertainty no longer has to mean that my judgement is invalid." },
      tool: "contextual_tension",
      toolData: { tensionPosition: 36, leftLabel: "My own direction", rightLabel: "What is already secure", leftContext: "After testing one reversible step.", rightContext: "When the choice is treated as final.", difference: "A small real test gave me information without requiring a final commitment.", think: "", feel: "", fear: "", want: "", unsaid: "", keepUnsaidPrivate: true },
      nextStep: "Keep the test reversible long enough to notice what becomes clearer.",
      outcome: "resolved_only",
      createdAt: "2026-08-29T09:00:00.000Z",
      updatedAt: "2026-08-29T09:10:00.000Z",
    },
    {
      id: "session-career-aug12",
      input: "I keep postponing whether to stay on this team. The role is stable, but it doesn't feel like a decision I made.",
      context: "decision",
      state: "COMPLETE",
      clarification: "The hardest part is disappointing people who backed me.",
      structure: { reality: "The offer is stable and familiar.", expectation: "People I respect expect me to stay.", selfDoubt: "I am unsure whether wanting something else is a good enough reason." },
      tool: "contextual_tension",
      toolData: { tensionPosition: 62, leftLabel: "My own direction", rightLabel: "What is already secure", leftContext: "When I can explore without closing every door.", rightContext: "When other people are affected by my choice.", difference: "This time, staying would be easier to explain than wanting to stay.", think: "", feel: "", fear: "", want: "", unsaid: "", keepUnsaidPrivate: true },
      nextStep: "Write down what I would choose if nobody needed an explanation.",
      outcome: "contextualized",
      createdAt: "2026-08-12T10:00:00.000Z",
      updatedAt: "2026-08-12T10:24:00.000Z",
    },
    {
      id: "session-school-aug20",
      input: "A mentor questioned my plan and I immediately stopped trusting it.",
      context: "repeating",
      state: "COMPLETE",
      structure: { reality: "A mentor raised a practical concern.", expectation: "Their approval matters to me.", selfDoubt: "I treated disagreement as evidence that my preference was invalid." },
      tool: "perspective_split",
      toolData: { tensionPosition: 48, leftLabel: "My judgement", rightLabel: "External validation", leftContext: "", rightContext: "", difference: "", think: "Their point may be useful.", feel: "Smaller than I did before the conversation.", fear: "Being seen as naive.", want: "To keep evaluating without handing over the decision.", unsaid: "", keepUnsaidPrivate: true },
      nextStep: "Separate the practical concern from the verdict I imagined.",
      outcome: "accepted",
      createdAt: "2026-08-20T08:00:00.000Z",
      updatedAt: "2026-08-20T08:18:00.000Z",
    },
  ],
  stateSnapshots: [
    { id: "snapshot-pressure-aug12", sessionId: "session-career-aug12", metricKey: "pressure", label: "Pressure", value: 4, source: "user_self_report", context: "Career decision", contextKey: "decision", capturedAt: "2026-08-12T10:05:00.000Z" },
    { id: "snapshot-clarity-aug12", sessionId: "session-career-aug12", metricKey: "clarity", label: "Clarity", value: 2, source: "user_self_report", context: "Career decision", contextKey: "decision", capturedAt: "2026-08-12T10:05:00.000Z" },
    { id: "snapshot-pressure-aug20", sessionId: "session-school-aug20", metricKey: "pressure", label: "Pressure", value: 3, source: "user_self_report", context: "Career decision", contextKey: "decision", capturedAt: "2026-08-20T08:04:00.000Z" },
    { id: "snapshot-clarity-aug20", sessionId: "session-school-aug20", metricKey: "clarity", label: "Clarity", value: 3, source: "user_self_report", context: "Career decision", contextKey: "decision", capturedAt: "2026-08-20T08:04:00.000Z" },
    { id: "snapshot-pressure-aug29", sessionId: "session-career-aug29", metricKey: "pressure", label: "Pressure", value: 2, source: "user_self_report", context: "Career decision", contextKey: "decision", capturedAt: "2026-08-29T09:02:00.000Z" },
    { id: "snapshot-clarity-aug29", sessionId: "session-career-aug29", metricKey: "clarity", label: "Clarity", value: 4, source: "user_self_report", context: "Career decision", contextKey: "decision", capturedAt: "2026-08-29T09:02:00.000Z" },
  ],
  facts: [
    { id: "fact-internship", statement: "I am currently in a six-month product internship.", context: "Career", createdAt: "2026-08-05T08:00:00.000Z", updatedAt: now, forgotten: false },
    { id: "fact-school", statement: "I can return to school next term without losing my place.", context: "School", createdAt: "2026-08-12T10:00:00.000Z", updatedAt: now, forgotten: false },
    { id: "fact-mentor", statement: "A mentor whose opinion matters to me questioned my plan.", context: "School", createdAt: "2026-08-20T08:00:00.000Z", updatedAt: now, forgotten: false },
  ],
  observations: [
    { id: "obs-validation", statement: "External approval appeared in three reflections about decisions.", sourceSessionIds: ["session-career-aug12", "session-school-aug20"], createdAt: now, disputed: false, forgotten: false },
    { id: "obs-delay", statement: "You named what you wanted after first explaining what would be safest.", sourceSessionIds: ["session-career-aug12"], createdAt: now, disputed: false, forgotten: false },
  ],
  insights: [
    {
      id: "insight-judgement",
      category: "tensions",
      title: "Judgement and validation",
      statement: "When your preference conflicts with someone important to you, you may start questioning whether your preference is valid.",
      status: "context_dependent",
      appliesWhen: ["The other person has expertise or has invested in me", "The choice affects an important relationship"],
      doesNotApplyWhen: ["I have direct experience and enough time to test my view"],
      evidenceIds: ["ev-career", "ev-school", "ev-project-counter"],
      firstSeenAt: "2026-08-12T10:24:00.000Z",
      lastRevisedAt: "2026-08-20T08:18:00.000Z",
      createdSource: "agent",
      userConfirmed: true,
    },
    {
      id: "insight-clarity",
      category: "what_i_need",
      title: "Room before commitment",
      statement: "In consequential choices, a reversible first step often helps you hear your own preference more clearly.",
      status: "user_confirmed",
      appliesWhen: ["The decision can be tested without pretending it is final"],
      doesNotApplyWhen: ["A decision has an immediate, irreversible deadline"],
      evidenceIds: ["ev-experiment", "ev-deadline-counter"],
      firstSeenAt: "2026-08-07T09:00:00.000Z",
      lastRevisedAt: "2026-08-18T09:00:00.000Z",
      createdSource: "user",
      userConfirmed: true,
    },
    {
      id: "insight-unsaid",
      category: "patterns",
      title: "Managing the reaction first",
      statement: "You sometimes edit what you want to say before you know how the other person will respond.",
      status: "recurring_signal",
      appliesWhen: ["The relationship feels important"],
      doesNotApplyWhen: ["The disagreement is low stakes"],
      evidenceIds: ["ev-unsaid-one", "ev-unsaid-two"],
      firstSeenAt: "2026-08-09T11:00:00.000Z",
      lastRevisedAt: "2026-08-24T11:00:00.000Z",
      createdSource: "agent",
      userConfirmed: true,
    },
    {
      id: "insight-changing",
      category: "boundaries",
      title: "Speaking before certainty",
      statement: "You may be becoming more willing to name a boundary before you can guarantee that it will be received well.",
      status: "changing",
      appliesWhen: ["You have had time to name what is yours to decide"],
      doesNotApplyWhen: ["You feel responsible for the other person's immediate reaction"],
      evidenceIds: ["ev-boundary-new", "ev-boundary-old"],
      firstSeenAt: "2026-08-14T11:00:00.000Z",
      lastRevisedAt: "2026-08-26T11:00:00.000Z",
      createdSource: "agent",
      userConfirmed: true,
    },
  ],
  evidence: [
    { id: "ev-career", insightId: "insight-judgement", sourceType: "reflection", sourceId: "session-career-aug12", excerpt: "Staying would be easier to explain than wanting to stay.", relationship: "supporting", context: "Career · Aug 12", createdAt: "2026-08-12T10:20:00.000Z" },
    { id: "ev-school", insightId: "insight-judgement", sourceType: "reflection", sourceId: "session-school-aug20", excerpt: "I treated disagreement as evidence that my preference was invalid.", relationship: "supporting", context: "School · Aug 20", createdAt: "2026-08-20T08:15:00.000Z" },
    { id: "ev-project-counter", insightId: "insight-judgement", sourceType: "observation", sourceId: "obs-validation", excerpt: "In one project decision, you kept your view after a teammate disagreed and tested it directly.", relationship: "counter_signal", context: "Project · Aug 16", createdAt: "2026-08-16T15:00:00.000Z" },
    { id: "ev-experiment", insightId: "insight-clarity", sourceType: "reflection", sourceId: "session-career-aug12", excerpt: "A two-week trial made the choice feel clearer without making it final.", relationship: "supporting", context: "Career · Aug 18", createdAt: "2026-08-18T09:00:00.000Z" },
    { id: "ev-deadline-counter", insightId: "insight-clarity", sourceType: "fact", sourceId: "fact-school", excerpt: "When the deadline was fixed, more options created noise rather than clarity.", relationship: "counter_signal", context: "School · Aug 11", createdAt: "2026-08-11T09:00:00.000Z" },
    { id: "ev-unsaid-one", insightId: "insight-unsaid", sourceType: "reflection", sourceId: "session-career-aug12", excerpt: "I rehearsed a version that would be easiest for them to hear.", relationship: "supporting", context: "Career · Aug 12", createdAt: "2026-08-12T10:00:00.000Z" },
    { id: "ev-unsaid-two", insightId: "insight-unsaid", sourceType: "reflection", sourceId: "session-school-aug20", excerpt: "I removed the part where I disagreed with my mentor.", relationship: "supporting", context: "School · Aug 20", createdAt: "2026-08-20T08:00:00.000Z" },
    { id: "ev-boundary-new", insightId: "insight-changing", sourceType: "reflection", sourceId: "session-school-aug20", excerpt: "I said I needed a day before answering instead of agreeing immediately.", relationship: "supporting", context: "Relationship · Aug 26", createdAt: "2026-08-26T11:00:00.000Z" },
    { id: "ev-boundary-old", insightId: "insight-changing", sourceType: "observation", sourceId: "obs-delay", excerpt: "In earlier reflections, you usually answered first and noticed the boundary later.", relationship: "counter_signal", context: "Across earlier reflections", createdAt: "2026-08-14T11:00:00.000Z" },
  ],
  versions: [
    { id: "ver-judgement-1", insightId: "insight-judgement", versionNumber: 1, statement: "I stop trusting my decisions when someone disagrees.", appliesWhen: [], doesNotApplyWhen: [], changedBy: "agent", createdAt: "2026-08-12T10:24:00.000Z" },
    { id: "ver-judgement-2", insightId: "insight-judgement", versionNumber: 2, statement: "When your preference conflicts with someone important to you, you may start questioning whether your preference is valid.", appliesWhen: ["The other person has expertise or has invested in me"], doesNotApplyWhen: ["I have direct experience and enough time to test my view"], changedBy: "user", changeReason: "It is specific to people whose judgement carries weight.", createdAt: "2026-08-20T08:18:00.000Z" },
    { id: "ver-boundary-1", insightId: "insight-changing", versionNumber: 1, statement: "I avoid setting boundaries.", appliesWhen: [], doesNotApplyWhen: [], changedBy: "agent", createdAt: "2026-08-14T11:00:00.000Z" },
    { id: "ver-boundary-2", insightId: "insight-changing", versionNumber: 2, statement: "You may be becoming more willing to name a boundary before you can guarantee that it will be received well.", appliesWhen: ["You have had time to name what is yours to decide"], doesNotApplyWhen: ["You feel responsible for the other person's immediate reaction"], changedBy: "user", createdAt: "2026-08-26T11:00:00.000Z" },
  ],
  rejectedInterpretations: [
    { id: "reject-always-conflict", candidateId: "candidate-always-conflict", statement: "You generally avoid conflict because disagreement feels unsafe.", context: "Project collaboration", rejectedAt: "2026-08-16T15:10:00.000Z" },
  ],
  journey: [
    { id: "journey-judgement-new", type: "new_understanding", insightId: "insight-judgement", title: "A possible pattern entered your mirror", summary: "External disagreement and trust in your own preference appeared connected.", currentStatement: "I stop trusting my decisions when someone disagrees.", createdAt: "2026-08-12T10:24:00.000Z", changedBy: "agent" },
    { id: "journey-judgement-refined", type: "refined_understanding", insightId: "insight-judgement", title: "You made the context more precise", summary: "The pattern became specific to people whose judgement carries weight.", previousStatement: "I stop trusting my decisions when someone disagrees.", currentStatement: "When your preference conflicts with someone important to you, you may start questioning whether your preference is valid.", createdAt: "2026-08-20T08:18:00.000Z", changedBy: "user" },
    { id: "journey-boundary-change", type: "understanding_changed", insightId: "insight-changing", title: "A previous understanding may be changing", summary: "New evidence complicates the idea that you always wait to name a boundary.", previousStatement: "I avoid setting boundaries.", currentStatement: "You may be becoming more willing to name a boundary before you can guarantee that it will be received well.", createdAt: "2026-08-26T11:00:00.000Z", changedBy: "user" },
  ],
  directions: [
    { id: "direction-judgement", statement: "Trust my judgement before asking for validation.", status: "still_matters", updatedAt: now },
  ],
  analytics: [],
};

export function createDemoState(): LivingModelState {
  return structuredClone(DEMO_STATE);
}

export function createEmptyState(): LivingModelState {
  return {
    schemaVersion: 1,
    mode: "demo",
    agentRuntimeStatus: "unavailable",
    onboarded: false,
    onboardingReasons: [],
    sampleDataLoaded: false,
    hasPersonalUnderstanding: false,
    memoryPaused: false,
    preferences: { tone: 50, depth: 50, practicalSuggestions: true, notes: "" },
    sessions: [],
    stateSnapshots: [],
    facts: [],
    observations: [],
    insights: [],
    evidence: [],
    versions: [],
    rejectedInterpretations: [],
    journey: [],
    directions: [],
    analytics: [],
  };
}
